kubernetes-sigs/kro

cmd/controller/main.go, internal/controller/resourcegroup/controller.go
By switching to the newer ObjectReconciler interface from controller-runtime we can remove some unnecessary logic to fetch/check that the resource we are reconciling actually exists.
=> Convert ResourceGroup to ObjectReconciler

examples/ack-controller/ec2-controller/ec2-controller.yaml, examples/ack-controller/eks-controller/eks-controller.yaml, examples/ack-controller/iam-controller/iam-controller.yaml
Remove duplicate ports section in ack controller deployment resources.
=> ack-controller example: remove duplicate ports section

internal/graph/parser/parser.go, internal/graph/parser/parser_test.go
Add support for the `x-kubernetes-preserve-unknown-fields` Kubernetes schema extension.
When this extension is present and set to true in a schema, skip parsing the object
and return an empty list of expressions.
This extension is commonly used in Kubernetes CRDs to allow for arbitrary nested
fields that shouldn't be validated against the schema.
=> parser: Add support for `x-kubernetes-preserve-unknown-fields` schema extension

website/docusaurus.config.ts
Fixes the `edit this page` link at the bottom of the kro.run website doc/examples.
=> Fix: update `edit this page` by updating docusaurus.config.ts

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go
Fixes https://github.com/awslabs/kro/issues/162
Merge after #174 
Previously, fields marked with `x-kubernetes-preserve-unknown-fields` were skipped
during parsing. Now these fields are parsed to extract expressions, allowing for
variable substitution in schemaless fields while still preserving unknown fields
as specified by the k8s-open-api extension.
=> feat: parse expressions in `x-kubernetes-preserve-unknown` fields

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go
*Issue #78:*
Added parsing of simple types int and bool to parseScalarTypes method.
=> feat(78): add simpleschema short spec types int and bool

pkg/graph/emulator/emulator.go, pkg/graph/emulator/emulator_test.go
Fixes #168 
*Description of changes:* Adding support for `x-kubernetes-int-or-string: true` in the dummy CR generator and a test case for that.  Based on discussion of changes [here](https://github.com/awslabs/kro/issues/168#issuecomment-2578021187)
=> adding support for `x-kubernetes-int-or-string` in dummy CR

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go, pkg/graph/parser/schemaless.go, pkg/graph/parser/schemaless_test.go, pkg/graph/variable/variable.go
fixes #181 
- In`FieldDescriptor` convert `ExpectedType` to `ExpectedTypes` of type `[]string` 
- `getExpectedType` returns `[]string` of all valid types
- `isExpectedType` utility function verifies is the type is valid
=> Add support for multiple expected types by converting `expectedtype` from `string` to `[]string`

api/v1alpha1/resource_group.go, config/crd/bases/kro.run_resourcegroups.yaml, helm/crds/kro.run_resourcegroups.yaml, pkg/controller/resourcegroup/controller_cleanup.go, pkg/graph/builder.go, pkg/graph/crd/crd.go, pkg/metadata/groupversion.go
*Issue #, if available:* #164
*Description of changes:* 
- Adding `Group string` to the schema in [kro/api/v1alpha1/resource_group.go](https://github.com/awslabs/kro/blob/main/api/v1alpha1/resource_group.go#L50)
- Passing this information to the `buildInstanceResource` function in [kro/internal/graph /builder.go](https://github.com/awslabs/kro/blob/main/internal/graph/builder.go#L192)
- Further passing this info to `SynthesizeCRD` in [kro/internal/graph /builder.go](https://github.com/awslabs/kro/blob/main/internal/graph/builder.go#L454) to get the new CRD which would have the group info.
- Updating the [extractCRDName](https://github.com/awslabs/kro/blob/main/internal/controller/resourcegroup/controller_cleanup.go) function to accomodate the newly added Group field during deletion.
- …
=> made group name configurable within resourcegroup

examples/webstack/instance-tmpl.yaml
*Issue #, if available:*
The instructions in README and variable name used in the `instance-tmpl.yaml` don't match. This PR matches what's in the readme.
=> fix: Correct env name in webstack instance-tmpl.yaml

pkg/controller/resourcegroup/controller_cleanup.go, pkg/graph/crd/crd.go
Add fallback to KroDomainName when group is not specified in
resource group controller and CRD synthesis. This ensures
consistent behavior when creating CRDs without an explicit group name.
The change affects two components:
- ResourceGroup reconciler: Set default group during cleanup
- CRD synthesis: Use default group when generating new CRDs
=> resourcegroup: use default KroDomainName when group is empty

pkg/controller/instance/controller_reconcile.go, pkg/controller/instance/delta/delta.go, pkg/controller/instance/delta/delta_test.go, pkg/controller/resourcegroup/controller.go, test/integration/suites/ackekscluster/suite_test.go, test/integration/suites/core/lifecycle_test.go, test/integration/suites/core/setup_test.go
Up until now, we weren't really doing proper diffing when deciding whether to update
managed resources - we just marked everything as "SYNCED". This patch adds a new delta
package that does a proper deep comparison between desired and observed resource
states, being careful about all the k8s metadata fields that we should ignore during
comparisons (e.g `metadata.generation`, `metadta.revision` etc...)
A key design aspect of this implementation is that `kro` only diffs fields that are
explicitly defined in `ResourceGroup` - any field that is defaulted by other
controllers or mutating webhooks are ignored. This ensures `kro` coexists seamlessly
with other reconciliation systems without fighting over field ownership.
The delta `Compare` function takes the desired and observed …
=> feat(core): track and apply resource changes through deep diffing

api/v1alpha1/types.go, config/crd/bases/kro.run_resourcegraphdefinitions.yaml, helm/crds/kro.run_resourcegraphdefinitions.yaml
Previous commit renamed the CRD but the author forgot to regenerate
the manifests. This commit:
- Regenerates CRD manifests for the previous rename
- Updates shortName from 'rg' to 'rgd'
=> chore: regenerate CRDs and update shortName to 'rgd'

README.md
We don't need the AWS questions in the README any longer. Longer term, we could use a more broad update of the README.
=> update readme, drop aws-isms

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go
This change improves type resolution 
for complex schemas that use OneOf with required/not patterns while also 
maintaining explicit type information.
`Key changes`:
- Detects and combines structural constraints with explicit types
- Ensures object type is included when required/not patterns are present
- Maintains backward compatibility for existing OneOf schemas
`Key insight`: Structural constraints like `required` and `not` can only be applied to 
objects since they operate on field presence/absence. Therefore, any schema using these 
constraints must be treated as an object type, even if not explicitly declared.
=> Infer `object` type from `OneOf` structural constraints `required/not patterns`

examples/gcp/README.md
Changed text that was pasted from an outdated doc
=> Update GCP examples README.md

NOTICE, cmd/controller/main.go, pkg/cel/environment.go, pkg/controller/instance/controller.go, pkg/controller/instance/controller_reconcile.go, pkg/controller/instance/controller_status.go, pkg/controller/instance/delta/delta.go, pkg/controller/instance/delta/delta_test.go, pkg/controller/instance/instance_state.go, pkg/controller/instance/metrics.go, pkg/controller/resourcegraphdefinition/controller.go, pkg/controller/resourcegraphdefinition/controller_cleanup.go, pkg/controller/resourcegraphdefinition/controller_reconcile.go, pkg/controller/resourcegraphdefinition/controller_status.go, pkg/dynamiccontroller/dynamic_controller.go, pkg/dynamiccontroller/metrics.go, pkg/graph/dag/dag.go, pkg/graph/resource_test.go, pkg/metadata/selectors.go, pkg/testutil/generator/resourcegraphdefinition.go, pkg/testutil/k8s/discovery.go, test/integration/suites/core/conditional_test.go, test/integration/suites/core/garbage_collection_test.go, test/integration/suites/core/lifecycle_test.go, test/integration/suites/core/readiness_test.go, test/integration/suites/core/recover_test.go, test/integration/suites/core/setup_test.go, test/integration/suites/core/status_test.go, test/integration/suites/core/topology_test.go, test/integration/suites/core/validation_test.go
- Replace AWS-hosted Apache 2.0 license URL with official apache.org URL across all source files
- Remove NOTICE file
=> chore: update license references to official Apache 2.0 URL

examples/aws/eks-cluster-mgmt/clusters/rg/vpc.yaml, examples/aws/webstack/Readme.md, examples/kubernetes/webapp/Readme.md, test/README.md, website/docs/docs/getting-started/02-deploy-a-resource-graph-definition.md, website/docs/docs/overview.md, website/docs/examples/web-app-ingress.md
Update documentation to consistently use "RGD" (Resource Graph Definition) instead of "RG"
=> docs: fix RGD abbreviations in docs

pkg/graph/builder.go, pkg/graph/builder_test.go, pkg/graph/dag/dag.go, pkg/graph/dag/dag_test.go, pkg/graph/resource.go, test/integration/suites/ackekscluster/generator.go, test/integration/suites/core/conditional_test.go, test/integration/suites/core/topology_test.go, test/integration/suites/networkingstack/generator.go
If there are no explicit dependencies between two nodes,
try to keep them in the same order.
By doing this, we can minimize the need for synthetic dependencies.
=> Tweak topological sort to preserve client-specified order

pkg/controller/instance/controller_reconcile.go
Testing the changes in https://github.com/kro-run/kro/pull/173 - even though resource updates do seem to work, the finalizers are removed from the updated resource.
This will add finalizers, if any are defined.
=> Copy finalizers from observed to desired object on resource update

examples/aws/serverless-microservice/README.md, website/docs/examples/aws/pod-rds-dbinstance.md, website/docs/examples/basic/noop.md, website/docs/examples/basic/web-app.md
The basic examples and a few others don't work anymore. The schema must have moved on from when this project started. Brought them back up to current schema.
=> Fix examples with old schema

pkg/graph/validation.go
'schema' is reserved as it's used to reference instance fields (e.g `schema.spec.name` || `schema.metadata.name`)
=> add 'schema' to kro reserved keywords list

.github/workflows/github-release.yaml
Add GitHub Action workflow to automatically create releases when a new version tag is pushed.
=> ci: add github release workflow

pkg/controller/resourcegraphdefinition/controller_reconcile.go, pkg/metadata/labels.go
In relation to issue #185, we should add KRO management labels to CRD's created via ResourceGraphDefinitions.
Example label output from `example/webapp/rg.yaml`
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
creationTimestamp: "2025-02-08T04:53:40Z"
generation: 1
labels:
kro.run/controller-pod-id: kro-pod
kro.run/kro-version: 0.2.1
kro.run/owned: "true"
kro.run/resource-graph-definition-id: f25ffd07-df0c-4c7e-b90e-507c80d317fc
kro.run/resource-graph-definition-name: webapp.kro.run
name: webapps.kro.run
resourceVersion: "33637"
uid: 0e3fdd78-bafe-4bca-b44e-9cb6e23dce58
```
=> Implement KRO Labels For RGD CRDs

helm/values.yaml
The Kro application uses port 8078 for metrics (via the -metrics-bind-address parameter). Therefore, this port should be specified as metricsport in the deployment configuration. Otherwise, metrics cannot be properly fetched.
This PR fixes: [kro-run/kro#294](https://github.com/kro-run/kro/issues/294)
=> fix: helm fix metrics port

pkg/graph/emulator/emulator.go
Add resourceVersion in the dummy object so that referencing metadata.resourceVersion does not throw an error when validating the RGD.
fixes #300
Using tests defined in https://github.com/kro-run/kro/pull/290
```
❯ go test -v ./test/e2e/suites/advanced/...
=== RUN   TestSecretsInResources
using_secrets_test.go:27: Using namespace: e2e-secrets-in-resources-1739398489, from: testdata/../../../../test/e2e/testdata/secrets-in-resources
testcase.go:193: Running step0: Install RGD and verify that the RGD is active
testcase.go:359:    Applying ResourceGraphDefinition/deployment-with-secret-rgd[rgd.yaml]
verify.go:57:       Verifying ResourceGraphDefinition/deployment-with-secret-rgd[0rgd.yaml]
verify.go:57:       Verifying CustomResourceDefinition/deploymentwithsecrets.kro.run[1instancecrd.yaml] …
```
=> Allow referencing metadata.resourceVersion in the RGD resources

pkg/metadata/groupversion.go
Fixes #305
Fixes #189 
Relates to bug #305 - Blocks #198
=> fix: ensure informers are cleaned up when ResourceGraphDefinitions are deleted

helm/templates/deployment.yaml, helm/values.yaml
The current helm chart values file is missing multiple controller argument flags. This merge requests adds the missing flags as options in the chart.
=> Add helm support for existing controller flags

examples/aws/webstack/Readme.md
The examples structure was changed causing some of the webstack readme instructions to fail.
=> examples directory location change fix

examples/aws/webstack/Readme.md, examples/aws/webstack/instance-tmpl.yaml
clusterName` is a required field to achieve pod identity association. If the user's cluster name is not 'kro' then pod identity association will fail and we will get output as "unhealthy"
=> clusterName field addition to avoid podidentity error

website/docs/docs/overview.md
👋 This removes an errant comma from the kro overview published at https://kro.run/docs/overview. Thanks!
=> chore: fix grammar typo in overview docs

pkg/graph/emulator/emulator.go, pkg/graph/emulator/emulator_test.go
Handle missing type in schema (generateObject) when x-kubernetes-preserve-unknown-fields is present.
CI checks are passing on my copy/fork of the repo: https://github.com/jknutson/kro/actions
I added a test, but did not include a type check; I did not feel that the goal here was to ensure a specific type.
If it would be valuable, I can add a test to ensure that we have an "object" returned.
This resolves https://github.com/kro-run/kro/issues/319; the failed RGD reconciles as soon as I start up the controller with this change.
=> fix: handle x-kubernetes-preserve-unknown-fields

examples/aws/llm/llm.yaml
Storage Class is Cluster scoped.
=> Remove `metadata.namespace` for LLM storage class example

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go
Previously, the parser only handled structural constraints (Required and Not) for OneOf schemas, but not for AnyOf schemas. This inconsistency could lead to incorrect type inference when parsing resources with AnyOf schemas that contain structural constraints.
- Modified the schema parser to handle structural constraints in AnyOf schemas the same way as OneOf schemas
- Extracted common logic for handling subschemas into `collectTypesFromSubSchemas` function
- Added comprehensive unit tests to verify the behavior of structural constraint handling in both OneOf and AnyOf schemas
=> Handle structural constraints in AnyOf schemas consistently with OneOf

website/docusaurus.config.ts
Fixes #353 
This PR adds support for a Go vanity import path for kro.run/pkg/..., allowing developers to import Kro modules using our own domain instead of the GitHub URL.
=> feat: add header configuration to allow vanity go imports

pkg/controller/resourcegraphdefinition/controller.go, pkg/metadata/labels.go
This label is not really useful since pod IDs change in HA setups, making the label meaningless.
=> Remove controller-pod-id label

api/v1alpha1/groupversion_info.go, pkg/controller/resourcegraphdefinition/controller.go, pkg/controller/resourcegraphdefinition/controller_cleanup.go, pkg/graph/crd/crd.go, pkg/metadata/finalizers.go, pkg/metadata/groupversion.go, pkg/metadata/labels.go, pkg/metadata/labels_test.go, test/integration/suites/ackekscluster/generator.go, test/integration/suites/core/conditional_test.go, test/integration/suites/core/lifecycle_test.go, test/integration/suites/core/readiness_test.go, test/integration/suites/core/recover_test.go, test/integration/suites/deploymentservice/generator.go, test/integration/suites/networkingstack/generator.go
Use uppercase for the KRO acronym throughout the codebase for consistency with
Go style guide: https://google.github.io/styleguide/go/decisions#initialisms
=> standardize `kro/KRO` capitalization per Go style guide

website/README.md
- I updated website/README.md file to link to docusaurus documentation in case users are using a different package manager than npm.
=> Update website README file

helm/templates/cluster-role-binding.yaml, helm/templates/cluster-role.yaml, helm/values.yaml, website/docs/docs/concepts/20-access-control.md
This PR introduces a new scheme for configuring RBAC through the Helm chart.
The basic approach mimics [what Kyverno does](https://kyverno.io/docs/installation/customization/#role-based-access-controls), so there is some industry precedent for this approach, and the aggregation feature it relies on is [long-time supported in Kubernetes](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles).
To enable this in your deployment, set
```yaml
rbac:
legacy: false
```
in your `values.yaml` file. You'll then need to create `ClusterRole`s with the label `rbac.kro.run/aggregate-to-controller: "true"` to grant any access you want to give Kro outside the bare-minimum set of permissions the Helm chart will now include.
Fixes #230.
=> feat: Fine-grained RBAC in the Helm chart

.ko.yaml, Makefile, pkg/controller/resourcegraphdefinition/controller.go, pkg/metadata/labels.go, pkg/version.go
Add support for injecting version information at build time via ldflags. This includes:
- Version, git commit hash, and build date injection in `.ko.yaml`
- Updated metadata labeler to use dynamic version
- Makefile updates to support version info injection
=> feat: add go ldflags for version info injection

helm/Chart.yaml, helm/values.yaml
Update the helm chart version to 0.2.2, preparing for the next patch release.
=> bump chart version to 0.2.2

.github/workflows/build-push-image.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/integration-tests.yaml, .github/workflows/unit-tests.yaml
Add path filters to only trigger Go related workflows when relevant files change:
- **.go files
- go.mod
- go.sum
(except golangci-lint which is only needed for .go file changes)
=> ci: add Go path filters to Go related workflows

pkg/graph/crd/crd_test.go
Adds unit tests for `pkg/graph/crd/crd.go` file
cc: @a-hilaly
=> Tests: adds unit tests for `pkg/graph/crd`

Makefile
Upon following the guide https://github.com/kro-run/kro/blob/main/docs/developer-getting-started.md#running-the-controller-inside-a-kind-cluster-with-ko
The makefile command `KIND_CLUSTER_NAME=kro make deploy-kind` was failing This PR will resolve those issues.
Fixes: #399 
cc: @a-hilaly
=> fix: makefile: deploy-kind command

pkg/graph/parser/parser_test.go
Fixes #398 
Before there was unused  ExpectedTypes field and ExpectedSchema mismatch
After 
Tested the code with 
go test ./pkg/graph/parser -v
which shows all test cases passed 
so currently it uses everyExpectedTypes field so no  ExpectedSchema mismatch in parser_test.go  and everything works fine
cc:@a-hilaly
=> Cleanup : unused `ExpectedTypes` field and `ExpectedSchema` mismatch in `parser_test.go`

pkg/graph/parser/cel.go, pkg/graph/parser/cel_test.go
This PR is Related to #291
This commit enhances the expression parser to properly handle nested expressions when they appear inside string literals, adding string literal tracking and escape sequence handling while still rejecting unquoted nested expressions.
=> feat: allow escaped nested expressions

cmd/controller/main.go, pkg/controller/instance/controller.go, pkg/dynamiccontroller/dynamic_controller.go, pkg/graph/builder.go, pkg/graph/dag/dag.go, pkg/metadata/labels.go
This PR fixes some typos in code comments:
- `parametes` -> `parameters`
- `recnociliation` -> `reconciliation`
- `instanciator` -> `instantiator`
- `Staticc` -> `Static`
- `exauhst` -> `exhaust`
- `deinitions` -> `definitions`
- `emualting` -> `emulating`
- `unmashal` -> `unmarshal`
- `posible` -> `possible`
- `simplicy` -> `simplicity`
=> chore: fix typos in code comments

pkg/client/set.go
Replace hardcoded version in user agent with dynamically linked version from `pkg.Version`.
=> feat: use dynamic version in user agent string

pkg/version.go, test/integration/suites/deploymentservice/suite_test.go
Set default "unknown" values for Version, GitCommit, and BuildDate
variables to ensure proper functionality when built without ldflags.
=> feat: set default version values and add version label tests

helm/Chart.yaml, helm/values.yaml
The current release automation substitue the correct version values during the build/release process.
=> chore: replace hardcoded versions with ${VERSION} placeholders

GOVERNANCE.md, examples/aws/ack-controller/README.md, examples/aws/webstack/Readme.md, test/README.md
This PR fixes some typos in documentation:
- `Orchestratory` -> `Orchestrator`
- `Conbined` -> `Combined`
- `Netsted` -> `Nested`
- `seperation` -> `separation`
- `Addional` -> `Additional`
=> chore: fix typos in documentation

pkg/graph/builder.go, pkg/graph/dag/dag.go, pkg/graph/dag/dag_test.go, pkg/graph/graph.go
allows usage of the DAG with potentially other data types if used as a library.
This is useful if dependency graphs are used for vertexes other than strings (e.g. ints which are used as identities or hashes).
I know this doesn't really benefit KROs internal use directly but it should not harm it either and opens up potential for reuse.
=> chore: migrate dag to cmp.Ordered

pkg/graph/validation_test.go
This PR adds one new unit test function, reaching 100% test coverage.
The current coverage of `validateResourceGraphDefinitionNamingConventions` is 83.3%, but there is no test function for that. The coverage was high because it was being called by another function (`NewResourceGraphDefinition`) in builder.go .
<details><summary>before the commit</summary>
```
% go test -coverprofile=coverage.out ./... > /dev/null                           
% go tool cover -func=coverage.out | grep graph/validation
github.com/kro-run/kro/pkg/graph/validation.go:68:						isValidResourceID					100.0%
github.com/kro-run/kro/pkg/graph/validation.go:73:						isValidKindName						100.0%
github.com/kro-run/kro/pkg/graph/validation.go:78:						isKROReservedWord					100.0% …
```
=> chore: increase test coverage `pkg/graph/validation.go` to 100%

pkg/metadata/labels_test.go
This PR adds 3 new unit test functions and fix a test case structure of `pkg/metadata/labels.go`, reaching 100% test coverage.
<details><summary>before the commit</summary>
```
% go test -coverprofile=coverage.out ./... > /dev/null                           
% go tool cover -func=coverage.out | grep labels.go  
github.com/kro-run/kro/pkg/metadata/labels.go:48:						IsKROOwned						100.0%
github.com/kro-run/kro/pkg/metadata/labels.go:54:						SetKROOwned						100.0%
github.com/kro-run/kro/pkg/metadata/labels.go:59:						SetKROUnowned						100.0%
github.com/kro-run/kro/pkg/metadata/labels.go:82:						Labels							100.0%
github.com/kro-run/kro/pkg/metadata/labels.go:87:						ApplyLabels						100.0%
github.com/kro-run/kro/pkg/metadata/labels.go:95:						Merge							100.0% …
```
=> chore: increase test coverage of `pkg/metadata/labels.go` to 100%

pkg/client/set.go, pkg/controller/resourcegraphdefinition/controller_status.go
This PR fix imports order according to standard ordering in Go.
The following command was performed to find and fix the problems:
```
goimports -w -local github.com/kro-run/kro ./pkg
```
=> chore: fix imports according to standard ordering in Go

GOVERNANCE.md
Fix broken code of conduct link in `GOVERNANCE.md`
=> docs: fix broken code of conduct link

pkg/graph/builder_test.go
This PR adds a new test case to TestGraphBuilder_Validation to check if the proper the error is returned when `RGD.Spec.Schema.Kind` is invalid.
=> chore: add test case to TestGraphBuilder_Validation

pkg/dynamiccontroller/dynamic_controller_test.go
This PR replaces the deprecated package `io/ioutil` by `io` (see [details](https://cs.opensource.google/go/go/+/master:src/io/ioutil/ioutil.go;l=7-10?q=ioutil&ss=go%2Fgo)).
=> chore: replace deprecated package `io/ioutil` by `io`

pkg/simpleschema/atomic.go, pkg/simpleschema/markers.go, pkg/simpleschema/transform.go, pkg/simpleschema/transform_test.go
1. Adds Enum Support to pkg simpleschema
2. Adds relevant tests cases for the same
fixes #304
=> pkg simpleschema: adds SimpleSchema enum support

pkg/controller/resourcegraphdefinition/controller.go
Bugged me a bit that there are double logging
example:
Each other log call is done in their respective method
https://github.com/kro-run/kro/blob/0b438927cf198fd02f9a22d309d4ebc6490795b7/pkg/controller/resourcegraphdefinition/controller_cleanup.go#L33-L35
https://github.com/kro-run/kro/blob/0b438927cf198fd02f9a22d309d4ebc6490795b7/pkg/controller/resourcegraphdefinition/controller_status.go#L161-L163
https://github.com/kro-run/kro/blob/0b438927cf198fd02f9a22d309d4ebc6490795b7/pkg/controller/resourcegraphdefinition/controller_status.go#L145-L147
https://github.com/kro-run/kro/blob/0b438927cf198fd02f9a22d309d4ebc6490795b7/pkg/controller/resourcegraphdefinition/controller_reconcile.go#L36-L40
https://github.com/kro-run/kro/blob/0b438927cf198fd02f9a22d309d4ebc6490795b7/pkg/controller/resourcegr …
=> chore: remove unnecessary logging during resource graph definition reconciliation

go.mod, go.sum
Bump `golang.org/x/oauth2` version to v0.28.0
=> Bump `golang.org/x/oauth2` version to v0.28.0

pkg/simpleschema/transform_test.go
This PR adds a new negative test case to TestLoadPredefinedTypes, in order to check the error return. It was needed to add a test cases array to be able to declare multiple test cases.
- Due to the minor nature of the changes, I didn't open a GitHub issue.
- The same change was proposed in [PR #447](https://github.com/kro-run/kro/pull/447), but for some unknown reason, the LINT workflow was not passing.
=> chore: add test case to TestLoadPredefinedTypes

pkg/graph/builder.go, pkg/graph/builder_test.go
The graph builder was attempting to access emulatedObject on resources without checking if it exists first. Since CRDs don't have emulated objects, this was causing a panic when any CEL expressions were present in the resource graph.
By adding conditional lookup on resource.emulatedObject . Avoiding null pointer dereference when working with types that dont have it: `apiextensions.k8s.io, v1, CustomResourceDefinition` in [builder.go#L286](https://github.com/kro-run/kro/blob/4a5b2a310b77fbd43f1babfaac53116d309e8980/pkg/graph/builder.go#L286)
Resolving #461
=> Fix nil pointer panic when evaluating CEL expressions with CRDs

Makefile, pkg/runtime/interfaces.go, pkg/runtime/runtime_test.go
I did not quote the ld flags in the #452 which resulted in:
```
go build -ldflags=-buildid= -X sigs.k8s.io/release-utils/version.gitVersion=v0.2.2-61-g35cb149-dirty -X sigs.k8s.io/release-utils/version.gitCommit=35cb149374379118d83c5ea619c6b93053577415 -X sigs.k8s.io/release-utils/version.gitTreeState="clean" -X sigs.k8s.io/release-utils/version.buildDate=none -o bin/controller ./cmd/controller/main.go
flag provided but not defined: -X
```
This quotes the `LDFLAGS` makefile var
=> Fix make build rule

cmd/controller/main.go, pkg/client/crd.go, pkg/client/set.go, pkg/controller/resourcegraphdefinition/controller.go, pkg/controller/resourcegraphdefinition/controller_cleanup.go, pkg/controller/resourcegraphdefinition/controller_reconcile.go, pkg/controller/resourcegraphdefinition/controller_status.go, pkg/runtime/runtime_test.go, test/integration/environment/setup.go
Leverages the context to grab the correct logger for each method that uses a logger in ResourceGraphDefinition controller.
Old log lines:
```
kro-86944cdcf6-l5td8 kro 2025-03-24T20:58:13.410Z	DEBUG	controller.resourceGraphDefinition	updating resource graph definition status	{"resourcegraphdefinition": {"name":"noop"}, "state": "Inactive", "conditions": 3}
kro-5d77854d9f-gtqmd kro 2025-03-24T21:31:02.982Z	LEVEL(-5)	Reconcile successful	{"controller": "resourcegraphdefinition", "controllerGroup": "kro.run", "controllerKind": "ResourceGraphDefinition", "ResourceGraphDefinition": {"name":"deploymentservice"}, "namespace": "", "name": "deploymentservice", "reconcileID": "579ac0e9-0902-4dcc-b220-8d104df1e911"}
```
New log lines:
```
kro-db65c46d7-q9r6g kro 2025-03-27T21:37:27.670Z	DEBUG …
```
=> Do not store loggers in controller stucts

website/src/css/custom.css
=> Fix: Home page buttons spacing on mobile devices

pkg/graph/builder.go, pkg/graph/builder_test.go
Refactoring the dryRunExpressions portion of builder.go
=> refactor: DryRunExpressions in builder.go

pkg/simpleschema/markers.go, pkg/simpleschema/transform.go, pkg/simpleschema/transform_test.go
1. Adds simple CEL validation support
2. Adds test cases corresponding to the changes
related to: https://github.com/kro-run/kro/issues/347 & https://github.com/kro-run/kro/pull/477
=> pkg simpleschema: Add simple CEL validation support

pkg/graph/fieldpath/parser.go, pkg/graph/fieldpath/parser_test.go
Field names with just a single letter, say 'data.A' for a data field in a configmap would result in an infinite loop.
=> Fix infinite loop in fieldPath parser for single-letter field names

pkg/simpleschema/field.go, pkg/simpleschema/field_test.go
The CEL expressions in a validation marker can use `||` for 'or' expressions. Therefore, the test for at most two elements would fail in these cases. Fix is to just split once.
Related to #347.
=> Fix field schema parsing

cmd/controller/main.go, helm/values.yaml
change the dynamic controller resync period unit from hours to seconds, allowing users to
configure much more frequent resyncs when needed for sensitive applications.
=> fix: change dynamic controller resync period unit from hours to seconds

pkg/runtime/runtime.go, pkg/runtime/runtime_test.go, test/integration/suites/core/includeWhen_test.go
Description of changes:
These changes address the failures that happen when the
controller attempts to evaluate a static expression that the
user does not want to include, with includeWhen expression 
evaluating to false.
=> fix: evaluate includeWhen before static expressions in runtime

website/docs/docs/governance.md
Add a new governance.md file that documents the CNCF governance model for kro,
including links to governance model, maintainers list, code of conduct,
contributing guidelines, and license.
Co-authored-by: Micah Hausler <mhausler@amazon.com>
=> docs: add governance page to website

api/v1alpha1/types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/kro.run_resourcegraphdefinitions.yaml, helm/crds/kro.run_resourcegraphdefinitions.yaml, pkg/graph/builder.go, pkg/simpleschema/simplerschema.go, pkg/simpleschema/transform.go, pkg/simpleschema/transform_test.go, website/docs/docs/concepts/10-simple-schema.md
This is the first implementation that was discussed in the slack channel. The other idea of having the `types` field in the `spec` part of the schema, seems to be more complicated to implement.
Fixes #144.
=> feat: Add support for (custom) types

cmd/controller/main.go, pkg/controller/resourcegraphdefinition/controller.go, test/integration/suites/core/crd_test.go
Add a watch for `v1.CustomResourceDefinition` updates to immediately reconcile
the owning `ResourceGraphDefinition` when a CRD is manually modified.
This ensures that any external modifications to CRDs are detected and automatically
reverted to maintain consistency with their ResourceGraphDefinition specifications.
Many thanks to Roi Nisimi <roi.nisimi@orca.security> for catching and reporting this one!
Co-authored-by: Roi Nisimi <roi.nisimi@orca.security>
=> feat: Add CRD watch to trigger `ResourceGraphDefinition` reconciliation

pkg/client/set.go
Currently, all clients create their own http client. 
Sharing a single http client allows these clients to share, among other things, a connection pool which poses a slight performance and memory optimisation.
=> feat: share http client

pkg/simpleschema/transform.go, pkg/simpleschema/transform_test.go
**NOTE**: Solves the issue [#167](https://github.com/kro-run/kro/issues/167)
*  Run Kro with the code from `main branch` commit `a563cef282f0e0968b0be1465090e3a523c0328a` 
* Deploy RGD from official KRO website, [Deploy Your First ResourceGraphDefinition](https://kro.run/docs/getting-started/deploy-a-resource-graph-definition)
* Deploy the following CR instance:
`instance.yaml`
```yaml
apiVersion: kro.run/v1alpha1
kind: Application
metadata:
name: my-application-instance
spec:
name: my-awesome-app
```
It is expected that deployed CR instance has parameter and value `ingress.enabled: false`, as this is default value. However, this parameter is missing in the CR instance.
* Run Kro with the code from `PR`
* cleanup from the test above
```sh
kubectl delete applications …
```
=> Nested default values in rgd schema

pkg/cel/ast/inspector.go, pkg/cel/environment.go
This allows to use base64.decode and base64.encode in CEL expressions, useful since reading secrets with externalRef doesn't decode their contents, e.g.:
```yaml
spec:
resources:  
- id: readSecret
externalRef:
apiVersion: v1
kind: Secret
metadata:
name: mySecret
namespace: myNs
- id: res1
template:
apiVersion: v1
kind: ConfigMap
metadata:
name: myConfigMap
data:
encoded: ${readSecret.data.something}
decoded: ${string(base64.decode(readSecret.data.something))}
somethingElseEncoded: ${base64.encode(b'Hello')}
```
=> Add base64 encoder to cel expression evaluation

helm/templates/cluster-role.yaml, helm/templates/deployment.yaml
For boolean cmd flags, they should only be set when the desired functionality is enabled, otherwise they should be omitted. 
The fix here conditionally sets the below two boolean flags based on the Values provided via helm.
- --allow-crd-deletion
- --leader-elect
**_Note:_** left the environment variable setup unchanged per conversation here where they were added. https://github.com/kro-run/kro/pull/275#discussion_r1951759915
With corrected enabling of leader-election, an RBAC issue arises when running with `mode: aggregation` which is also addressed here. Adds the rules from config [leader_election_role](https://github.com/kro-run/kro/blob/3b37c6b462940a979b2c221ca51f83e3fdf4763a/config/rbac/leader_election_role.yaml#L13) to the helm chart.
Address helm issue: #595
=> [helm] fix: conditionally provide bool args and corrected RBAC for aggregation mode

pkg/metadata/groupversion.go
It seems that flect.Pluralize() doesn't always return the same result, depending on it if the passed string is lowercase or not.
When creating a RGD with `spec.schema.kind: ExampleSOS` 
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
name: my-application
spec:
schema:
apiVersion: v1alpha1
kind: ExampleSOS
spec:
name: string
image: string | default="nginx"
...
```
It appears that flect.Pluralize() returns different result when Kro is [creating CRD](https://github.com/kro-run/kro/blob/main/pkg/graph/crd/crd.go#L39)
and when Kro looks for the [created CRD](https://github.com/kro-run/kro/blob/main/pkg/metadata/groupversion.go#L91-L92)
Therefore Kro throws exception as it can not find the resource examplesoses:
```log
W0708 19:40:45.150168   35461 reflector.go:561] …
```
=> Inconsistency in flect pluralize causing that Kro can't find the CRD

pkg/simpleschema/transform.go, pkg/simpleschema/transform_test.go
It will now check the values and handle them accordingly. The truthy values are "true", "yes", and "1". The supported falsey values are "false" and "no".
Any other value will return an error.
=> Fix required marker value handling

pkg/cel/conversions.go, pkg/runtime/runtime_test.go
**Why we need this**
The changes to `GoNativeType()` in https://github.com/kro-run/kro/pull/525 lead to optional values not underlying the same type restrictions as non-optional values. For an optional, a value of type `map[int]interface{}` would be returned, while for a non-optional, it would return an error (see added test cases).
This PR aligns the behaviour of `GoNativeType()` for optional values with non-optional values.
> @a-hilaly is there a particular reason to restrict the allowed types to this set? Otherwise, we might want to think about completely removing `GoNativeTypes()` and replace its calls with `v.Value()` (essentially, only replacing https://github.com/kro-run/kro/blob/6255087b2c49ac2f1542d0366e39d13d9acf054a/pkg/runtime/runtime.go#L586 with `return val.Value(), nil`). …
=> chore: improve optional type handling and error reporting in GoNativeType

cmd/kro/commands/generate.go
Command to generate kro RGDs dummy instances
`kro generate instance -f [FILE]`
Flags:
| Shorthand | Flag | Usage | 
| ---- | ----- | --- |
| -f |  --file | Path to the ResourceGroupDefinition file |
[Screencast from 2025-07-15 23-44-11.webm](https://github.com/user-attachments/assets/d582b582-f0f4-465c-92c3-947c615c127e)
=> kro cli generate instance

MAINTAINERS.md
Thanks to @jlbutler for the update in https://github.com/kro-run/kro/pull/641. I'm offering these additional changes:
- As discussed in the previous PR, listing past maintainers as emeritus.
- Removing unused column as it only adds confusion due to being empty.
=> Adding emeritus; removing empty column

.github/workflows/stale-bot.yaml
This workflow runs daily at 03:17 UTC and can be triggered manually. It:
* Uses **actions/stale\@v9** to manage inactive issues and pull requests.
* Labels issues/PRs as `stale` after **30 days of inactivity**, unless they carry the `keepalive` label.
* Issues are **never auto-closed** (only marked stale).
* PRs are **auto-closed after 60 days** of inactivity, with a notice that they can be reopened.
* Maintainers get hygiene reminders via messages when items go stale.
* Limits processing to 50 items per run and removes stale labels if activity resumes.
fix https://github.com/kro-run/kro/issues/620
=> chore(ci): add stale bot workflow for issue and PR management

test/e2e/chainsaw/check-instance-update/deployment-update-assert.yaml
Recently k8s removed the defaulting for creationTimestamp.
https://github.com/kubernetes/kubernetes/pull/130989
This defaulting change percolated to kind version 1.30 in our tests and caused the test breakage
=> Remove some defaulting fields in deployment spec for tests

pkg/simpleschema/markers.go, pkg/simpleschema/markers_test.go, pkg/simpleschema/transform.go, pkg/simpleschema/transform_test.go, test/e2e/chainsaw/check-validation-markers/README.md, test/e2e/chainsaw/check-validation-markers/chainsaw-test.yaml, test/e2e/chainsaw/check-validation-markers/configmap-assert.yaml, test/e2e/chainsaw/check-validation-markers/instancecrd-assert.yaml, test/e2e/chainsaw/check-validation-markers/invalid-instance-array-limits.yaml, test/e2e/chainsaw/check-validation-markers/invalid-instance-max-items.yaml, test/e2e/chainsaw/check-validation-markers/invalid-instance-min-items.yaml, test/e2e/chainsaw/check-validation-markers/invalid-instance-priorities-max.yaml, test/e2e/chainsaw/check-validation-markers/invalid-length-error.yaml, test/e2e/chainsaw/check-validation-markers/invalid-length-instance.yaml, test/e2e/chainsaw/check-validation-markers/invalid-pattern-error.yaml, test/e2e/chainsaw/check-validation-markers/invalid-pattern-instance.yaml, test/e2e/chainsaw/check-validation-markers/invalid-unique-error.yaml, test/e2e/chainsaw/check-validation-markers/invalid-unique-instance.yaml, test/e2e/chainsaw/check-validation-markers/rgd-assert.yaml, test/e2e/chainsaw/check-validation-markers/rgd.yaml, test/e2e/chainsaw/check-validation-markers/valid-instance-assert.yaml, test/e2e/chainsaw/check-validation-markers/valid-instance.yaml, website/docs/docs/concepts/10-simple-schema.md
Hi
I noticed that simpleschema currently doesn’t support some common string-related JSON Schema markers such as pattern, minLength, and maxLength.
Since these are widely used in k8s, I was a bit surprised they weren’t already supported.
In this PR i added new marker types: pattern, minLength, maxLength and uniqueItems
Question for the maintainers:
Is there a specific reason why these markers were not supported so far (e.g., intentionally left out), or was it more a case of “not yet implemented”?
I opened this PR mainly to start the discussion. If these markers are welcome, I’d be happy to extend the PR with docs and tests.
Thanks for the feedback 🙏
=> feat(simpleschema): add support for pattern, minLength, maxLengt, uniqueItems, maxItems and minItems markers

cmd/controller/main.go
- Use descriptive lease name "kro-controller" instead of "6f0f64a5..."
=> fix!: use kro-controller as leaderElectionID 

test/integration/suites/core/nested_test.go
Adds integration tests that verify:
- Nested `ResourceGraphDefinition` lifecycle including creation, status updates, and cleanup
- Dynamic creation of RGDs with different schema field types (integer, string, boolean)
=> test(core): RGDs all the way down

pkg/controller/resourcegraphdefinition/controller_cleanup.go, pkg/controller/resourcegraphdefinition/controller_reconcile.go, pkg/dynamiccontroller/dynamic_controller.go, pkg/dynamiccontroller/dynamic_controller_test.go
While playing around with dynamic controller, I noticed that our names were askew:
* StopServiceGVK
* StartServingGVK
I also noticed that our comments referred to a "registration" concept that is commonly used in controller runtime. Feel free to reject if there are any consumers of this that I am not aware of.
=> chore: Tidy up lack of parity on dynamic controller interface

pkg/dynamiccontroller/dynamic_controller.go
This small change makes the dynamic controller agnostic to RGDs.
I am using dynamic controller for a similar use case to KRO (using CRDs to spawn watches on other CRDs). The library is exactly what I'm looking for, but I am making a few tweaks along the way. I am not treating this as a public interface, and am completely happy if you break these interfaces without a version bump.
=> chore: Make dynamic controller logging object-type agnostic.

pkg/controller/instance/controller.go, pkg/dynamiccontroller/dynamic_controller.go
Simplified how we're using NamespacedNames to more naturally integrate for DynamicController consumers.
Tested manually by creating an RGD, RG, and deleting both.
=> fix: Use controllerruntime's namespaced name correctly

.github/workflows/postsubmit.yaml
Modules don't land in goproxy until they are depended on by another package and pulled through the proxy. Some corporate firewalls (...) synchronize from go proxy, and until packages are hydrated there, they cannot be reflected into internal build systems. This change automates that pull and makes sure the proxy always has the latest version.
See: https://github.com/awslabs/operatorpkg/blob/main/.github/workflows/postsubmit.yaml
=> chore: Hydrate goproxy after each push
