internal/runtime/runtime.go, internal/runtime/runtime_test.go, test/integration/suites/core/conditional_test.go
=> Fix: allow referencing dynamic and static variables in one field

website/docs/examples/pod-rds-dbinstance.md
Neat Project. 
Just fixing the GVK of the RDS example. 
---
=> Fix: pod-rds-dbinstance.md rds service GVK

README.md
=> Update slack channel link in README

website/docusaurus.config.ts
=> Update Slack link to Kubernetes channel in docusaurus config

internal/cel/conversions.go, internal/graph/parser/parser.go, internal/graph/parser/parser_test.go, test/integration/suites/core/readiness_test.go
=> Support null fields in ternary and field assignment

website/docusaurus.config.ts
This matches usage elsewhere in the repo.
=> chore: fix tagline resources -> resource

examples/data-processor/README.md
Added link to re:Invent 2024 breakout video that walks through this example
*Issue #, if available:*
=> Added link to demo video

website/src/css/custom.css, website/src/theme/Footer/footer.module.css, website/src/theme/Footer/index.tsx
Per discussion, update footer.
=> [nit] front page update for docs site

CONTRIBUTING.md
Fixes #177
*Description of changes:* Added info on how to run the project locally for development
=> update contributing doc with setup instructions

helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/metrics-service.yaml, helm/templates/serviceaccount.yaml, helm/values.yaml
Improvements were made in consideration of the scalability of the cord, key improvements are as follows.
1. Structural Consistency
- Redesigned the values.yaml file structure to be more logical and consistent
- Grouped related configurations (e.g., deployment, serviceAccount, metrics)
- Enhanced readability and manageability of configuration
2. Scalability Enhancement
- Improved the structure to allow easy custom configuration additions
- Enabled simple integration of new options while maintaining existing settings
- Implemented flexible configuration groups like extraVolumes and extraVolumeMounts
3. Clarity and Documentation
- Added clear, comprehensive English comments for each configuration option
- Provided Kubernetes documentation links for complex settings …
=> Refactoring kro helm templates

pkg/graph/emulator/emulator.go, pkg/graph/emulator/emulator_test.go
*Issue #, if available:*
generate value will generate a value from randomly from supported types
=> added `AnyOf` support to generate value for dummy CR

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go
Fixes https://github.com/awslabs/kro/issues/168
•	Added the constant xKubernetesIntOrString to detect if the CRD schema has the extension.
•	Updated parseString and parseScalarTypes to handle fields annotated with x-kubernetes-int-or-string, allowing them to be treated as either a string or an integer.
•	Added Test Cases function: TestXKubernetesIntOrString and TestNestedXKubernetesIntOrString
=> add  `x-kubernetes-int-or-string` support for parser

pkg/graph/parser/parser.go, pkg/graph/parser/parser_test.go
- Added support for `OneOf` and `AnyOf` to `getExpectedTypes` ->  returns a slice of the options
- Updated `validateSchema` to remove  `OneOf` and `AnyOf` logic -> moved to `getExpectedTypes`
- added simple and nested testcases func `TestOneOfAndAnyOf`
=> added `OneOf` and `AnyOf` support for parser

pkg/graph/validation.go
Allow any string format for apiVersion and defer validation to API server.
=> feat: relax apiVersion validation

pkg/graph/builder.go
This check did not function properly for resources with multiple versions. Rather than depending on the GVK, we use just the GK, as a GK is either namespaced or not, it can't change between versions.
=> Fix resource namespaced check

examples/azure/storage-container/README.md, examples/azure/storage-container/instance.yaml, examples/azure/storage-container/rg.yaml, examples/azure/todo-app/README.md, examples/azure/todo-app/instance.yaml, examples/azure/todo-app/rg.yaml
Adds a few basic Azure examples using ASO.
=> Azure + ASO examples

README.md
The current link does not work
=> docs(readme): fix kro-concepts link

website/docs/docs/concepts/00-resource-group-definitions.md
Fixing this issue https://github.com/kro-run/kro/issues/280
=> Correct instance Kind in RGD concept page

website/docs/examples/aws/aws-examples.md
Add callout for ACK controller #286 for the Networking stack example
=> Add callout for ACK controller #286

examples/aws/llm/README.md, examples/aws/llm/instance.yaml, examples/aws/llm/llm.yaml
This PR introduces a **KRO ResourceGraphDefinition (RGD)** to deploy **Large Language Models** on **Amazon EKS** using **Ollama**.  
- **Automated Storage** (EBS-backed PVCs)  
-  **CPU & GPU Support** (Dynamic provisioning)  
-  **Ingress & Service** (ALB exposure)  
With **KRO + Ollama**, deploying LLMs on Kubernetes is **declarative, scalable, and efficient!**
=> Open-Source LLMs on EKS

pkg/dynamiccontroller/dynamic_controller.go
RateLimitingInterface is deprecated and should be removed with TypedRateLimitingInterface
=> Refactor dynamic controller queue to use typed rate limiting interface

.ko.yaml
Switch to smaller distroless/static base image.
=> chore: switch to distroless base image

README.md
This pull request adds relevant badges to the README.md file to enhance the repository's visibility and credibility. The badges provide useful information such as build status, license, contributors, and other key metrics, making the README more informative and professional.
- Added badges for key repository metrics (e.g., build status, license, stars, forks, go mod version, etc.).
- Improved the visual appeal and readability of the README.md file.
- Ensured proper formatting and alignment for better clarity.
**Why This Is Needed:**
- Badges make important repository details easily accessible.
- They improve the overall presentation and professionalism of the README.
- Helps new contributors and users quickly understand the project’s status and key metri
=> Added Relevent Readme Badges

pkg/graph/parser/parser.go
This PR solves issue #283 
Tested using local Kro development environment.
=> fix: improve number type validation to support int values

website/docusaurus.config.ts
- I added more footer links in community section for footer and included youtube channel link for recorded meetings.
- this pr will improve navigation and make more easier for user to access community resources.
=> Added more footer links to the website

CONTRIBUTING.md
Updates
- add getting started section
- fix typos and formatting with inconsistent spacing
=> update contribution.md, add getting started section

pkg/graph/parser/cel.go
fixes comments in https://github.com/kro-run/kro/pull/297
=> Make error descriptive for `ErrNestedExpression`

pkg/metadata/selectors_test.go
Adds unit tests for `graph/metadata/selectors.go` file
=> Tests: adds unit tests for `pkg graph/metadata/selectors.go`

examples/aws/ingress-triangle/README.md, examples/aws/ingress-triangle/application.yaml, examples/aws/ingress-triangle/ingress-triangle.yaml, examples/aws/ingress-triangle/instances/app1-ingress.yaml, examples/aws/ingress-triangle/instances/app2-ingress.yaml
Ingress Triangle RGD example with Instance
=> Adding ingress triangle example

pkg/cel/environment_test.go
Adds tests for `pkg/cel/environment.go` file
cc: @a-hilaly
=> Tests: adds tests for `cel/environment.go`

website/docs/docs/concepts/10-simple-schema.md
- s/number/float/
- Added more examples for simpleschema markers
=> Enhance simpleschema documentation

api/v1alpha1/conditions.go, go.mod, pkg/apis/condition.go, pkg/apis/condition_set.go, pkg/apis/condition_set_test.go, pkg/apis/condition_test.go, pkg/apis/condition_types.go, pkg/apis/condition_types_test.go
As mentioned in https://github.com/kro-run/kro/issues/458, this starts to land some of the helper code that deals with "top-level" conditions and sub-conditions. 
This does not get used in the controller yet. Just landing the fork and updated code. 
Sorry it is so large, the code is only about 300 lines, the rest is tests.
=> Fork and update of Condition Sets from Knative, attributed

examples/aws/alb-listener-tg/alb-tg-listener-instance.yaml, examples/aws/alb-listener-tg/alb-tg-listener.yaml
Adding RGD and Instance yaml files to provision ALB, TG and ListenerRule
=> Adding RGD and Instance yaml files to provision ALB, TG and ListenerRule

examples/kubernetes/job-example/instance.yaml, examples/kubernetes/job-example/rgd.yaml
Add an example showing how to create Jobs using KRO. Note we need to make sure the job stays by not setting any TTL
=> example: show and example using Job (set no ttl)

examples/gcp/gemma-on-tpu/README.md, examples/gcp/gemma-on-tpu/rgd.yaml
Adding a GCP Gemma on TPU Example. This uses Project as external reference
This example depends on : #273
=> GCP Gemma TPU Inference example

AGENTS.md, cmd/kro/main.go
fix enable_mutli_acct typo across examples
=> Fix typos 

Makefile, cmd/kro/commands/generate.go, cmd/kro/main.go
1. generates CRDs from input RGD files
2. prints the generated output either on terminal or creates a new file on the basis of flags given 
`kro generate crd -f [FILE]`
Flags:
| Shorthand | Flag | Usage | 
| ---- | ----- | --- |
| -f |  --file | Path to the ResourceGroupDefinition file |
| -F |  --format |   Output format (yaml/json) |
|  -o | --output  |   Path to the output file |
[Screencast from 2025-06-13 20-25-09.webm](https://github.com/user-attachments/assets/e0a2d8bb-d04c-4a43-b782-eb892dbb4a9d)
=> kro cli generate crd command

pkg/cel/ast/inspector.go, pkg/cel/environment_test.go
Instead of maintaining a list of known functions, let's ask the env.
The test contains a copy of the previous list, just to make sure, this doesn't break anything. Note that the collection functions are not functions but macros.
=> Use CEL env's HasFunction method

docs/design/proposals/status-conditions.md
=> Status conditions design to design dir

pkg/metadata/finalizers.go
Came as a comment in #561 
Pulling it out as a separate PR
=> refactor: use controller runtime helper functions for finalizers

NOTICE
CLA signed - removing from NOTICE.
=> CLA signed - removing from NOTICE

pkg/graph/validation.go
Following discussion of the new collections KREP, it would be prudent to reserve these potential keywords. Discussed with @a-hilaly offline.
=> !feat: Reserve item and items as keywords for collections
